Fix laptop view
USGS-VIZLAB/pools-and-fluxes pull request #33
Opened 2022-09-26 01:33 UTC by hcorson-dosch

This PR fixes #19 and fixes #21 and finalizes the interaction set up, which closes #11

The interaction rectangles are now appended to `this.svgChart` instead of the `this.svg`. As a result they now align with the chart elements on different window sizes.

Now on desktop the rectangles used to dim the chart do not cover the left margin, so do not dim the text. The text is now dimmed directly, per #21. However, I've set it up so the full left margin space is still used to trigger click and mouseover events on desktop.

The PR also adjust the height and width settings for the `chart-container` and restricts the width of the page content so that it's not really wide on huge monitors.

This PR also makes some adjustments to the font-sizing for the text at the top of the page as well as the y-axis text.

2022-09-26 15:14 UTC, ceenell commented
When on `linear` the mouseover is making non-selected rows half-hilighted 
<img width="435" alt="image" src="https://user-images.githubusercontent.com/17803537/192313713-a068491a-36d5-4c55-854b-18af695686b1.png">

The text could still use a little bit more hierarchy. What about increasing the weight of the title and the axis label, or just the words Pool and Flux where they appear? Also the text sizes for the top text and text below the chart are pretty different. The line spacing of the top text seems high compared to the rest of the page.

2022-09-26 15:16 UTC, ceenell commented on src/App.vue
>    font-weight: 300;
What about 700?

2022-09-26 15:19 UTC, ceenell commented on src/components/pool_flux_chart.vue
> -    font-weight: 500;
I think it could work well to bump the weight a little bit and make "pools" and "fluxes" pop throughout

2022-09-26 15:53 UTC, ceenell requested changes
Need to address half moons on desktop mouseover

2022-09-26 15:56 UTC, hcorson-dosch commented
> When on `linear` the mouseover is making non-selected rows half-hilighted <img alt="image" width="435" src="https://user-images.githubusercontent.com/17803537/192313713-a068491a-36d5-4c55-854b-18af695686b1.png">

👀 Good catch!! I'll fix that

> The text could still use a little bit more hierarchy. What about increasing the weight of the title and the axis label, or just the words Pool and Flux where they appear? 

Agreed that it needs more refinement. The words pool and flux are higher weight - I'll see if I can go higher.

> Also the text sizes for the top text and text below the chart are pretty different on desktop but look more consistent on mobile. The line spacing of the top text seems high compared to the rest of the page.

👍 I'll make some tweaks

2022-09-26 23:11 UTC, hcorson-dosch commented
Ok - changes made. I fixed the half-moon issue, made font sizes more consistent, and upped the emphasis of 'pool' and 'flux' throughout.

2022-09-27 13:59 UTC, ceenell commented on src/components/pool_flux_chart.vue
> +            .html("<p class='x_label'><span class='poolText emph'>Pool</span> volume (km³) or <span class='fluxText emph'>flux</span> rate (km³ per year)</p>")
🆒

2022-09-27 14:03 UTC, ceenell approved these changes
Great - everything ran for me locally and it's coming together.

2022-09-27 14:08 UTC, merged